[package]
name = "wickerman"
version = "0.1.0"
authors = ["Zach Mitchell <zmitchell@fastmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
proc-macro2 = {version = "^0.2.2", features = ["nightly"]}
syn = {version = "^0.12.12", features = ["full"]}

[lib]
proc-macro = true
